"""Added onboarding status

Revision ID: 5d37bd68c395
Revises: 5c962008e649
Create Date: 2025-11-15 17:41:30.478003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d37bd68c395'
down_revision = '5c962008e649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_registration', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
