"""Added featured property to Celebrity

Revision ID: b175d44420ab
Revises: 
Create Date: 2025-10-28 15:59:37.440215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b175d44420ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celebrity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celebrity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('featured')

    # ### end Alembic commands ###
